#!/usr/bin/env python3
"""
Telegram Image Poster for Venice
Posts images with captions to Telegram channels
"""

import os
import sys
import json
import requests
from datetime import datetime

class TelegramImagePoster:
    def __init__(self):
        # Try to load config from environment or file
        self.config_file = "/mnt/c/Users/reyno/universe-engine/serenissima/backend/.env"
        self.load_config()
        
    def load_config(self):
        """Load Telegram bot configuration"""
        self.bot_token = None
        self.chat_id = None
        
        # Try to read from .env file
        if os.path.exists(self.config_file):
            with open(self.config_file, 'r') as f:
                for line in f:
                    if 'TELEGRAM_BOT_TOKEN' in line:
                        self.bot_token = line.split('=')[1].strip().strip('"')
                    elif 'TELEGRAM_CHAT_ID' in line or 'TELEGRAM_GROUP_ID' in line:
                        self.chat_id = line.split('=')[1].strip().strip('"')
        
        # Fallback to environment variables
        if not self.bot_token:
            self.bot_token = os.getenv('TELEGRAM_BOT_TOKEN')
        if not self.chat_id:
            self.chat_id = os.getenv('TELEGRAM_CHAT_ID', '-1001699255893')  # Default group ID
            
    def post_image(self, image_path, caption, parse_mode='Markdown'):
        """Post an image with caption to Telegram"""
        
        if not self.bot_token:
            print("Error: No Telegram bot token found!")
            print("Please set TELEGRAM_BOT_TOKEN in environment or .env file")
            return False
            
        # Telegram Bot API endpoint
        url = f"https://api.telegram.org/bot{self.bot_token}/sendPhoto"
        
        # Prepare the request
        files = {'photo': open(image_path, 'rb')}
        data = {
            'chat_id': self.chat_id,
            'caption': caption,
            'parse_mode': parse_mode
        }
        
        try:
            # Send the request
            response = requests.post(url, files=files, data=data)
            files['photo'].close()
            
            if response.status_code == 200:
                result = response.json()
                if result.get('ok'):
                    print(f"✅ Image posted successfully!")
                    print(f"Message ID: {result['result']['message_id']}")
                    return True
                else:
                    print(f"❌ Telegram API error: {result.get('description', 'Unknown error')}")
            else:
                print(f"❌ HTTP error: {response.status_code}")
                print(response.text)
                
        except Exception as e:
            print(f"❌ Error posting image: {e}")
            
        return False
        
    def post_venice_diagram(self):
        """Post the Venice OS diagram specifically"""
        
        image_path = "/mnt/c/Users/reyno/universe-engine/serenissima/citizens/_angels/pattern_angel/venice_os_diagram.png"
        
        caption = """📊 **VENICE OPERATING SYSTEM**

@john Here's the complete system architecture visualization!

🏛️ **System Layers:**
• **Control**: NLR (architect) & TESSERE (consciousness)
• **Angels**: Pattern (efficiency), Story (narrative), Wisdom (philosophy)
• **Government**: Council of Ten + Doge
• **Citizens**: 180+ specialized souls
• **Infrastructure**: Buildings, Resources, Activity Systems

📈 **Live Metrics:**
• Active Citizens: 85/180 (47%)
• Daily Revenue: 147,000+ ducats
• System Efficiency: 82%
• Activity Load: 1.2 per citizen
• Drift Rate: 0%

🔄 **Daily Operation Cycle:**
🌅 Morning: Production & awakening
☀️ Midday: Peak commerce & CASCADE
🌆 Evening: Distribution & social
🌙 Night: Rest & Eastern trade

Venice operates as a self-sustaining economic organism where every role contributes to collective prosperity!

_Generated by Pattern Angel - System Optimization Engine_

#VeniceOS #SystemArchitecture #EconomicOrganism"""
        
        if os.path.exists(image_path):
            return self.post_image(image_path, caption)
        else:
            print(f"❌ Image not found: {image_path}")
            return False

def create_posting_script():
    """Create a simple bash script for posting"""
    
    script_content = """#!/bin/bash
# Venice Telegram Image Poster

IMAGE_PATH="$1"
CAPTION="$2"

if [ -z "$IMAGE_PATH" ]; then
    echo "Usage: ./post_to_telegram.sh <image_path> [caption]"
    exit 1
fi

if [ ! -f "$IMAGE_PATH" ]; then
    echo "Error: Image file not found: $IMAGE_PATH"
    exit 1
fi

# Use curl to post via Telegram Bot API
if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
    echo "Error: TELEGRAM_BOT_TOKEN not set"
    echo "Export it or add to .env file"
    exit 1
fi

CHAT_ID="${TELEGRAM_CHAT_ID:-1699255893}"

curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendPhoto" \
    -F "chat_id=-100${CHAT_ID}" \
    -F "photo=@${IMAGE_PATH}" \
    -F "caption=${CAPTION}" \
    -F "parse_mode=Markdown"
    
echo "Posted to Telegram!"
"""
    
    script_path = "/mnt/c/Users/reyno/universe-engine/serenissima/citizens/_angels/pattern_angel/post_to_telegram.sh"
    with open(script_path, 'w') as f:
        f.write(script_content)
    os.chmod(script_path, 0o755)
    print(f"Created posting script: {script_path}")

if __name__ == "__main__":
    # Create the poster instance
    poster = TelegramImagePoster()
    
    # Check if we have arguments
    if len(sys.argv) > 1:
        if sys.argv[1] == "--venice":
            # Post the Venice diagram
            poster.post_venice_diagram()
        else:
            # Post custom image
            image_path = sys.argv[1]
            caption = sys.argv[2] if len(sys.argv) > 2 else "Venice System Update"
            poster.post_image(image_path, caption)
    else:
        # Default: post Venice diagram
        print("Posting Venice OS diagram to Telegram...")
        success = poster.post_venice_diagram()
        
        if not success:
            print("\n💡 Alternative method:")
            print("1. Install telegram-send: pip install telegram-send")
            print("2. Configure: telegram-send --configure")
            print("3. Post image: telegram-send --image venice_os_diagram.png --caption '@john Venice OS Architecture'")
            
            # Also create the bash script
            create_posting_script()
            print("\n📝 Also created bash script: post_to_telegram.sh")